-- =========================================================
-- NORMALIZACAO DE SERVICOS: explode linhas multi-servico
-- Execute EM ORDEM, passo a passo
-- =========================================================

-- PASSO 1: Backup
-- =========================================================
CREATE TABLE BKP_TB_CONTRATO_PRE_NORMALIZACAO LIKE TB_CONTRATO;
INSERT INTO BKP_TB_CONTRATO_PRE_NORMALIZACAO SELECT * FROM TB_CONTRATO;

-- PASSO 2: Conferir backup
-- =========================================================
SELECT COUNT(*) AS total_bkp FROM BKP_TB_CONTRATO_PRE_NORMALIZACAO;
SELECT COUNT(*) AS total_original FROM TB_CONTRATO;

-- PASSO 3: Visualizar linhas que serao alteradas
-- =========================================================
SELECT
    ID_CONTRATO, COD_INSTITUICAO, SERVICOS_CONTRATADOS,
    NUM_AC_CONTRATADOS, FL_ACESSOS_ILIMITADOS, VALOR_EXCEDENTE
FROM TB_CONTRATO
WHERE INSTR(SERVICOS_CONTRATADOS, ',') > 0
ORDER BY COD_INSTITUICAO, SERVICOS_CONTRATADOS;

-- PASSO 4: Expandir "Individual, Lote, API"
--   Atualizar a linha atual para 'Individual'
--   Inserir 'Lote' e 'API' como novas linhas
-- =========================================================
UPDATE TB_CONTRATO
SET SERVICOS_CONTRATADOS = 'Individual'
WHERE SERVICOS_CONTRATADOS = 'Individual, Lote, API';

INSERT INTO TB_CONTRATO (
    COD_INSTITUICAO, COD_COMPARTILHADO, NUM_CONTRATO,
    DT_INI, DT_FIM, DT_CORTE_INICIAL, FREQUENCIA_CORTE,
    SERVICOS_CONTRATADOS, NUM_AC_CONTRATADOS,
    FL_ACESSOS_ILIMITADOS, VALOR_EXCEDENTE, FL_MONITORAR_CONTRATO
)
SELECT
    COD_INSTITUICAO, COD_COMPARTILHADO, NUM_CONTRATO,
    DT_INI, DT_FIM, DT_CORTE_INICIAL, FREQUENCIA_CORTE,
    'Lote', NUM_AC_CONTRATADOS,
    FL_ACESSOS_ILIMITADOS, VALOR_EXCEDENTE, FL_MONITORAR_CONTRATO
FROM BKP_TB_CONTRATO_PRE_NORMALIZACAO
WHERE SERVICOS_CONTRATADOS = 'Individual, Lote, API';

INSERT INTO TB_CONTRATO (
    COD_INSTITUICAO, COD_COMPARTILHADO, NUM_CONTRATO,
    DT_INI, DT_FIM, DT_CORTE_INICIAL, FREQUENCIA_CORTE,
    SERVICOS_CONTRATADOS, NUM_AC_CONTRATADOS,
    FL_ACESSOS_ILIMITADOS, VALOR_EXCEDENTE, FL_MONITORAR_CONTRATO
)
SELECT
    COD_INSTITUICAO, COD_COMPARTILHADO, NUM_CONTRATO,
    DT_INI, DT_FIM, DT_CORTE_INICIAL, FREQUENCIA_CORTE,
    'API', NUM_AC_CONTRATADOS,
    FL_ACESSOS_ILIMITADOS, VALOR_EXCEDENTE, FL_MONITORAR_CONTRATO
FROM BKP_TB_CONTRATO_PRE_NORMALIZACAO
WHERE SERVICOS_CONTRATADOS = 'Individual, Lote, API';

-- PASSO 5: Expandir "Individual, Lote"
-- =========================================================
UPDATE TB_CONTRATO
SET SERVICOS_CONTRATADOS = 'Individual'
WHERE SERVICOS_CONTRATADOS = 'Individual, Lote';

INSERT INTO TB_CONTRATO (
    COD_INSTITUICAO, COD_COMPARTILHADO, NUM_CONTRATO,
    DT_INI, DT_FIM, DT_CORTE_INICIAL, FREQUENCIA_CORTE,
    SERVICOS_CONTRATADOS, NUM_AC_CONTRATADOS,
    FL_ACESSOS_ILIMITADOS, VALOR_EXCEDENTE, FL_MONITORAR_CONTRATO
)
SELECT
    COD_INSTITUICAO, COD_COMPARTILHADO, NUM_CONTRATO,
    DT_INI, DT_FIM, DT_CORTE_INICIAL, FREQUENCIA_CORTE,
    'Lote', NUM_AC_CONTRATADOS,
    FL_ACESSOS_ILIMITADOS, VALOR_EXCEDENTE, FL_MONITORAR_CONTRATO
FROM BKP_TB_CONTRATO_PRE_NORMALIZACAO
WHERE SERVICOS_CONTRATADOS = 'Individual, Lote';

-- PASSO 6: Expandir "Individual, API"
-- =========================================================
UPDATE TB_CONTRATO
SET SERVICOS_CONTRATADOS = 'Individual'
WHERE SERVICOS_CONTRATADOS = 'Individual, API';

INSERT INTO TB_CONTRATO (
    COD_INSTITUICAO, COD_COMPARTILHADO, NUM_CONTRATO,
    DT_INI, DT_FIM, DT_CORTE_INICIAL, FREQUENCIA_CORTE,
    SERVICOS_CONTRATADOS, NUM_AC_CONTRATADOS,
    FL_ACESSOS_ILIMITADOS, VALOR_EXCEDENTE, FL_MONITORAR_CONTRATO
)
SELECT
    COD_INSTITUICAO, COD_COMPARTILHADO, NUM_CONTRATO,
    DT_INI, DT_FIM, DT_CORTE_INICIAL, FREQUENCIA_CORTE,
    'API', NUM_AC_CONTRATADOS,
    FL_ACESSOS_ILIMITADOS, VALOR_EXCEDENTE, FL_MONITORAR_CONTRATO
FROM BKP_TB_CONTRATO_PRE_NORMALIZACAO
WHERE SERVICOS_CONTRATADOS = 'Individual, API';

-- PASSO 7: Conferencia pos-expansao
-- =========================================================
SELECT 'Contagem' AS etapa, COUNT(*) AS total FROM TB_CONTRATO
UNION ALL
SELECT 'Multi-servico restantes', COUNT(*)
FROM TB_CONTRATO WHERE INSTR(SERVICOS_CONTRATADOS, ',') > 0;

SELECT SERVICOS_CONTRATADOS, COUNT(*) AS qtd
FROM TB_CONTRATO
GROUP BY SERVICOS_CONTRATADOS
ORDER BY SERVICOS_CONTRATADOS;
