-- Proposta de criacao e carga inicial da TB_CONTRATO.
-- NAO execute sem revisao/confirmacao explicita.
-- Fonte da carga inicial: TSV gerado a partir da planilha atual pelo script
-- scripts/export_contracts_staging_csv.py.

CREATE TABLE TB_CONTRATO (
    ID_CONTRATO BIGINT NOT NULL AUTO_INCREMENT,

    COD_INSTITUICAO DECIMAL(10,0) NOT NULL,
    COD_COMPARTILHADO DECIMAL(10,0) NULL,

    NUM_CONTRATO VARCHAR(50) NULL,

    DT_INI DATETIME NOT NULL,
    DT_FIM DATETIME NOT NULL,
    DT_CORTE_INICIAL DATETIME NOT NULL,

    FREQUENCIA_CORTE VARCHAR(20) NOT NULL,
    SERVICOS_CONTRATADOS VARCHAR(80) NOT NULL,

    NUM_AC_CONTRATADOS INT NULL,
    FL_ACESSOS_ILIMITADOS TINYINT(1) NOT NULL DEFAULT 0,

    VALOR_EXCEDENTE DECIMAL(12,2) NULL,
    FL_MONITORAR_CONTRATO TINYINT(1) NOT NULL DEFAULT 1,

    DT_CRIACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_ATUALIZACAO DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (ID_CONTRATO),
    INDEX IDX_TB_CONTRATO_COD_INSTITUICAO (COD_INSTITUICAO),
    INDEX IDX_TB_CONTRATO_COD_COMPARTILHADO (COD_COMPARTILHADO),
    INDEX IDX_TB_CONTRATO_MONITORAR (FL_MONITORAR_CONTRATO),
    INDEX IDX_TB_CONTRATO_DT_FIM (DT_FIM),
    INDEX IDX_TB_CONTRATO_CORTE (DT_CORTE_INICIAL, FREQUENCIA_CORTE),
    UNIQUE KEY UK_TB_CONTRATO_UNIDADE (
        COD_INSTITUICAO,
        NUM_CONTRATO,
        SERVICOS_CONTRATADOS
    )
);

CREATE TABLE STG_CONTRATO_PLANILHA (
    COD_INSTITUICAO DECIMAL(10,0) NOT NULL,
    COD_COMPARTILHADO DECIMAL(10,0) NULL,
    NOME_INSTITUICAO VARCHAR(150) NULL,
    NUM_CONTRATO VARCHAR(50) NULL,
    DT_CORTE_INICIAL DATETIME NOT NULL,
    FREQUENCIA_CORTE VARCHAR(20) NOT NULL,
    SERVICOS_CONTRATADOS VARCHAR(80) NOT NULL,
    NUM_AC_CONTRATADOS VARCHAR(50) NULL,
    VALOR_EXCEDENTE VARCHAR(50) NULL,
    FL_MONITORAR_CONTRATO TINYINT(1) NOT NULL DEFAULT 1
);

-- Ajuste o caminho do arquivo antes de executar no MySQL Workbench.
-- O TSV deve ser gerado com:
-- uv run python scripts/export_contracts_staging_csv.py --output /tmp/stg_contrato_planilha.tsv
-- O delimitador TAB evita conflito com campos que contem virgula, como
-- SERVICOS_CONTRATADOS = 'Individual, Lote, API'.
LOAD DATA LOCAL INFILE '/tmp/stg_contrato_planilha.tsv'
INTO TABLE STG_CONTRATO_PLANILHA
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' ENCLOSED BY '"' ESCAPED BY '\\'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    COD_INSTITUICAO,
    @COD_COMPARTILHADO,
    NOME_INSTITUICAO,
    NUM_CONTRATO,
    DT_CORTE_INICIAL,
    FREQUENCIA_CORTE,
    SERVICOS_CONTRATADOS,
    NUM_AC_CONTRATADOS,
    VALOR_EXCEDENTE,
    FL_MONITORAR_CONTRATO
)
SET COD_COMPARTILHADO = NULLIF(@COD_COMPARTILHADO, '');

-- Conferencia antes da carga definitiva.
SELECT COUNT(*) AS total_staging FROM STG_CONTRATO_PLANILHA;

SELECT
    COD_INSTITUICAO,
    COD_COMPARTILHADO,
    NUM_CONTRATO,
    DT_CORTE_INICIAL,
    FREQUENCIA_CORTE,
    SERVICOS_CONTRATADOS,
    NUM_AC_CONTRATADOS,
    VALOR_EXCEDENTE
FROM STG_CONTRATO_PLANILHA
ORDER BY COD_INSTITUICAO, NUM_CONTRATO
LIMIT 20;

INSERT INTO TB_CONTRATO (
    COD_INSTITUICAO,
    COD_COMPARTILHADO,
    NUM_CONTRATO,
    DT_INI,
    DT_FIM,
    DT_CORTE_INICIAL,
    FREQUENCIA_CORTE,
    SERVICOS_CONTRATADOS,
    NUM_AC_CONTRATADOS,
    FL_ACESSOS_ILIMITADOS,
    VALOR_EXCEDENTE,
    FL_MONITORAR_CONTRATO
)
SELECT
    s.COD_INSTITUICAO,
    s.COD_COMPARTILHADO,
    NULLIF(TRIM(s.NUM_CONTRATO), ''),
    i.DT_INI,
    i.DT_FIM,
    s.DT_CORTE_INICIAL,
    s.FREQUENCIA_CORTE,
    s.SERVICOS_CONTRATADOS,
    CASE
        WHEN UPPER(TRIM(COALESCE(s.NUM_AC_CONTRATADOS, ''))) = 'ILIMITADO' THEN NULL
        WHEN TRIM(COALESCE(s.NUM_AC_CONTRATADOS, '')) = '' THEN NULL
        ELSE CAST(REPLACE(REPLACE(s.NUM_AC_CONTRATADOS, '.', ''), ',', '.') AS UNSIGNED)
    END AS NUM_AC_CONTRATADOS,
    CASE
        WHEN UPPER(TRIM(COALESCE(s.NUM_AC_CONTRATADOS, ''))) = 'ILIMITADO' THEN 1
        ELSE 0
    END AS FL_ACESSOS_ILIMITADOS,
    CASE
        WHEN TRIM(COALESCE(s.VALOR_EXCEDENTE, '')) = '' THEN NULL
        WHEN REPLACE(
            REPLACE(
                REPLACE(
                    REPLACE(REPLACE(s.VALOR_EXCEDENTE, 'R$', ''), ' ', ''),
                    '.',
                    ''
                ),
                ',',
                ''
            ),
            '-',
            ''
        ) REGEXP '[^0-9]' THEN NULL
        WHEN REPLACE(REPLACE(s.VALOR_EXCEDENTE, 'R$', ''), ' ', '') LIKE '%,%' THEN
            CAST(
                REPLACE(
                    REPLACE(REPLACE(REPLACE(s.VALOR_EXCEDENTE, 'R$', ''), ' ', ''), '.', ''),
                    ',',
                    '.'
                ) AS DECIMAL(12,2)
            )
        ELSE CAST(REPLACE(REPLACE(s.VALOR_EXCEDENTE, 'R$', ''), ' ', '') AS DECIMAL(12,2))
    END AS VALOR_EXCEDENTE,
    s.FL_MONITORAR_CONTRATO
FROM STG_CONTRATO_PLANILHA s
JOIN TB_INSTITUICAO i
  ON i.COD_INSTITUICAO = s.COD_INSTITUICAO
WHERE i.DT_INI IS NOT NULL
  AND i.DT_FIM IS NOT NULL;

-- Conferencia apos carga.
SELECT COUNT(*) AS total_contratos FROM TB_CONTRATO;

SELECT
    c.ID_CONTRATO,
    c.COD_INSTITUICAO,
    i.NOME_INSTITUICAO,
    c.COD_COMPARTILHADO,
    c.NUM_CONTRATO,
    c.DT_INI,
    c.DT_FIM,
    c.DT_CORTE_INICIAL,
    c.FREQUENCIA_CORTE,
    c.SERVICOS_CONTRATADOS,
    c.NUM_AC_CONTRATADOS,
    c.FL_ACESSOS_ILIMITADOS,
    c.VALOR_EXCEDENTE,
    c.FL_MONITORAR_CONTRATO
FROM TB_CONTRATO c
LEFT JOIN TB_INSTITUICAO i
       ON i.COD_INSTITUICAO = c.COD_INSTITUICAO
ORDER BY c.COD_INSTITUICAO, c.NUM_CONTRATO
LIMIT 20;
